version: '3.5'

networks:
  fiber-network:
    external:
      name: fiber-network

services:
  fiber-api-1: # API - Instance 01
    image: fiber-api
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    expose:
      - "8000"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: '250MB'
    networks:
      default: {}
      fiber-network:
        aliases:
          - fiber-api-proxy-1

  fiber-api-2: # API - Instance 02
    image: fiber-api
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - db
    expose:
      - "8000"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: '250MB'
    networks:
      default: {}
      fiber-network:
        aliases:
          - fiber-api-proxy-2

  nginx: # Load Balancer
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fiber-api-1
      - fiber-api-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50MB'
    networks:
      default: {}
      fiber-network:
        aliases:
          - nginx-proxy

  db: # database
    image:  postgres:15.3-bullseye
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.4'
    #       memory: '1.75GB'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banco
    networks:
      default: {}
      fiber-network:
        aliases:
          - db-proxy
